# Generated by Django 4.0.4 on 2022-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
